name: melodica
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.3
  uuid: ^4.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/blob-background.svg

  fonts:
    - family: Hammersmith One
      fonts:
        - asset: assets/fonts/HammersmithOne-Regular.ttf

